version: '3'

services:
  db:
    image: postgres:12
    restart: unless-stopped
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ./init_db/init_db.sql:/docker-entrypoint-initdb.d/init_api_db.sql
    ports:
    - "5432:5432"