name: Build

env:
  TAG: v1.7

on:
  push:
  pull_request:
    branches: [ master, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - name: Build Docker server image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/server:${{ env.TAG }} --target api-server .
      - name: Push the server image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/api-server:${{ env.TAG }}